language: hi
pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  analyzer: 'char'  # use 'char' or 'char_wb' for character
- name: "EmbeddingIntentClassifier"
