NUMBERS = {
    'one': 'one',
    '1': 'one',
    'पहला': 'one',
    'first': 'one',
    '१': 'one',
    'ek': 'one',
    'एक': 'one',
    'पहला वाला': 'one',
    'option 1': 'one',
    'select 1': 'one',
    'नंबर १': 'one',
    'नंबर 1': 'one',
    '१  नंबर': 'one',
    '1 नंबर': 'one',
    'एक नंबर': 'one',
    'नंबर एक': 'one',
    'विकल्प 1': 'one',
    'option one': 'one',
    'choice 1': 'one',
    'first number': 'one',

    'two': 'two',
    '2': 'two',
    'दूसरा': 'two',
    'second': 'two',
    '२': 'two',
    'do': 'two',
    'दो': 'two',
    'दूसरा वाला': 'two',
    'option 2': 'two',
    'select 2': 'two',
    'नंबर २': 'two',
    'नंबर 2': 'two',
    '२ नंबर': 'two',
    '2 नंबर': 'two',
    'दो नंबर': 'two',
    'नंबर दो': 'two',
    'विकल्प 2': 'two',
    'option two': 'two',
    'choice 2': 'two',
    'second number': 'two',

    'three': 'three',
    '3': 'three',
    'तीसरा': 'three',
    'third': 'three',
    '३': 'three',
    'teen': 'three',
    'तीन': 'three',
    'तीसरा वाला': 'three',
    'option 3': 'three',
    'select 3': 'three',
    'नंबर ३': 'three',
    'नंबर 3': 'three',
    '३ नंबर': 'three',
    '3 नंबर': 'three',
    'तीन नंबर': 'three',
    'नंबर तिन': 'three',
    'विकल्प 3': 'three',
    'option three': 'three',
    'choice 3': 'three',
    'third number': 'three',

    'four': 'four',
    '4': 'four',
    'चौथा': 'four',
    'fourth': 'four',
    '४': 'four',
    'chaar': 'four',
    'चार': 'four',
    'चौथा वाला': 'four',
    'option 4': 'four',
    'select 4': 'four',
    'नंबर ४': 'four',
    'नंबर 4': 'four',
    '४ नंबर': 'four',
    '4 नंबर': 'four',
    'चार नंबर': 'four',
    'नंबर चार': 'four',
    'विकल्प 4': 'four',
    'option four': 'four',
    'choice 4': 'four',
    'fourth number': 'four',

    'five': 'five',
    '5': 'five',
    'पांचवा': 'five',
    'fifth': 'five',
    '५': 'five',
    'paanch': 'five',
    'पांच': 'five',
    'पांचवा वाला': 'five',
    'option 5': 'five',
    'select 5': 'five',
    'नंबर ५': 'five',
    'नंबर 5': 'five',
    '५ नंबर': 'five',
    '5 नंबर': 'five',
    'पांच  नंबर': 'five',
    'नंबर पांच': 'five',
    'विकल्प 5': 'five',
    'option five': 'five',
    'choice 5': 'five',
    'fifth number': 'five',

    'six': 'six',
    '6': 'six',
    'छठा': 'six',
    'sixth': 'six',
    '६': 'six',
    'chhah': 'six',
    'छे': 'six',
    'छठा वाला': 'six',
    'option 6': 'six',
    'select 6': 'six',
    'नंबर ६': 'six',
    'नंबर 6': 'six',
    '६  नंबर': 'six',
    '6 नंबर': 'six',
    'छह नंबर': 'six',
    'नंबर छह': 'six',
    'विकल्प 6': 'six',
    'option six': 'six',
    'choice 6': 'six',
    'sixth number': 'six',

    'seven': 'seven',
    '7': 'seven',
    'सातवा': 'seven',
    'seventh': 'seven',
    '७': 'seven',
    'saat': 'seven',
    'सात': 'seven',
    'सातवा वाला': 'seven',
    'option 7': 'seven',
    'select 7': 'seven',
    'नंबर ७': 'seven',
    'नंबर 7': 'seven',
    '७ नंबर': 'seven',
    '7 नंबर': 'seven',
    'सात नंबर': 'seven',
    'नंबर सात': 'seven',
    'विकल्प ७': 'seven',
    'option seven': 'seven',
    'choice 7': 'seven',
    'seventh number': 'seven',

    'eight': 'eight',
    '8': 'eight',
    'आठवां': 'eight',
    'eighth': 'eight',
    '८': 'eight',
    'aaath': 'eight',
    'आठ': 'eight',
    'आठवां वाला': 'eight',
    'option 8': 'eight',
    'select 8': 'eight',
    'नंबर ८': 'eight',
    'नंबर 8': 'eight',
    '८ नंबर': 'eight',
    '8 नंबर': 'eight',
    'आठ  नंबर': 'eight',
    'नंबर आठ': 'eight',
    'विकल्प ८': 'eight',
    'option eight': 'eight',
    'choice 8': 'eight',
    'eighth number': 'eight',

    'nine': 'nine',
    '9': 'nine',
    'नौवा': 'nine',
    'ninth': 'nine',
    '९': 'nine',
    'nou': 'nine',
    'नौ': 'nine',
    'नौवा वाला': 'nine',
    'option 9': 'nine',
    'select 9': 'nine',
    'नंबर ९': 'nine',
    'नंबर 9': 'nine',
    '९  नंबर': 'nine',
    '9 नंबर': 'nine',
    'नौ नंबर': 'nine',
    'नंबर नौ': 'nine',
    'विकल्प ९': 'nine',
    'option nine': 'nine',
    'choice 9': 'nine',
    'ninth number': 'nine',

    'ten': 'ten',
    '10': 'ten',
    'दसवा': 'ten',
    'tenth': 'ten',
    '१०': 'ten',
    'das': 'ten',
    'दस': 'ten',
    'दसवां वाला': 'ten',
    'option 10': 'ten',
    'select 10': 'ten',
    'नंबर १०': 'ten',
    'नंबर 10': 'ten',
    '१० नंबर': 'ten',
    '10 नंबर': 'ten',
    'दस नंबर': 'ten',
    'नंबर दस': 'ten',
    'विकल्प १०': 'ten',
    'option ten': 'ten',
    'choice 10': 'ten',
    'tenth number': 'ten',

    'हे': 'greet',
    'हेलो': 'greet',
    'हैल्लो': 'greet',
    'नमस्ते': 'greet',
    'प्रणाम': 'greet',
    'hey': 'greet',
    'haillo': 'greet',
    'namaste': 'greet',
    'namaskar': 'greet',
    'pranaam': 'greet',
    'paranaam': 'greet',
    'pranam': 'greet',
    'paranam': 'greet',
    'hello': 'greet',
    'hallo': 'greet',
    'halo': 'greet',
    'heelo': 'greet',
    'haloo': 'greet',
    'helo': 'greet',
    'परनाम': 'greet',
    'hello!': 'greet',
    'hello!!': 'greet',
    'hello..': 'greet',
    'hey.': 'greet',
    'hey..': 'greet',
    'hi': 'greet',
    'hi!': 'greet',
    'hi there': 'greet',

    'हां': 'yes',
    'हां।': 'yes',
    'haa': 'yes',
    'haan': 'yes',
    'ha': 'yes',
    'हूं': 'yes',
    'निश्चित रूप से': 'yes',
    'नितांत': 'yes',
    'निस्संदेह': 'yes',
    'ya': 'yes',
    'yes': 'yes',
    'ja': 'yes',
    'yup': 'yes',
    'yy': 'yes',
    'yeh': 'yes',
    'yeah': 'yes',
    'yep': 'yes',
    'ji': 'yes',
    'yo': 'yes',
    'yo!': 'yes',
    'पूर्णतया': 'yes',
    'अवश्यमेव': 'yes',
    'हाँ': 'yes',
    'क्यों नहीं': 'yes',
    'बिलकुल': 'yes',

    'ना': 'no',
    'नहीं': 'no',
    'नही': 'no',
    'नहि': 'no',
    'नाही': 'no',
    'नए': 'no',
    'नही जी': 'no',
    'na': 'no',
    'no': 'no',
    'nahi': 'no',
    'nope': 'no',
    'naa': 'no',
    'nah': 'no',
    'noo': 'no',
    'nahi ji': 'no',
    'नहीँ': 'no',
    'नो': 'no',
    # 'नौ': 'no',
    'कुछ भी नहीं': 'no',
    'इनकार': 'no',
    'कोई भी नहीं': 'no',
    'न': 'no',
    'तनिक भी नहीं': 'no',
    'बिलकुल नहीं': 'no',
    'नहीं चाइये': 'no',
}
